### ISSUE TITLE
Support for the Microbee disk image

### ISSUE THREAD

**Issue by v-retro** [keirf/FlashFloppy#105]
Someone has asked me whether the Gotek with FlashFloppy will support the Microbee computer.  I know very little about these but some references to the images can be found here:
https://www.microbee-mspp.org.au/wiki/tiki-index.php?page=Microbee#Software

I note that these have a .DSK extension.  Would this be the same file format as images supported for the Amstrad CPC computers?

**Comment by keirf** [comment]
Microbee is apparently a 10x512 CP/M format. Variants seem to be 40-cyl, 80-cyl and 1- or 2-sides. Will need some DSK and eg HFE images to see how the sector numbering is done. The DSK images are probably raw (like IMG). For ambiguous sizes (eg. 40-cyl, 2-side vs 80-cyl, 1-side) need to see if there is a info block within each disk image which can be used to disambiguate.

In summary it's nothing that special, just need some engagement and assistance from Microbee users to get the required info.

**Comment by staticmem** [comment]
@v-retro: There are a numbers of users on the MSPP forum that use Gotek with FF firmware and works fine.

The DSK images we use are the same format as the CPC images.  Tools we use to archive disk images use the LibDsk library which supports a number of different disk image formats. See: http://www.seasip.info/Unix/LibDsk/

Microbee disks are single or double sided using FM or MFM format,  normally use 10 sequentially numbered physical sectors in the sector headers numbered 1-10.  CP/M systems apply a skew factor of 3 to reduce the affects of disk rotation latency (i.e: 2, 5, 8, 1, 4, 7, 10, 3, 6, 9).  The Microbee uses the WD2793 FDC IC.  The native format programs in the day used side 0 in the sector header regardless of whether it was SS or DS.  The WD2793 was programmed to ignore the side value.  It's not clear why the correct side information was not used in the sector headers.

The lack of the correct DS side information when trying to read disks on a PC caused a problem reading the disks but could be overcome by fooling the the FDC and some custom software that used the PC's Parallel port to take over the role of the side select line.

The other issue with native Microbee formatted disks when being read on a PC is that there is not enough GAP bytes before the first sector after the Index pulse so some FDCs such as the uP765 refused to read the disk.  This is not an issue on controllers such as the WD2793, etc when programmed to ignore the value.

Early Microbee disks used Single Density.  Apart from what I mentioned above the track format follows that as specified by the WD2793 data sheet.

There are some 3.5" disks that use physical sectors numbered 21-30 on the data tracks (referred to as DS80 format) but the system tracks used 1-10 which meant the boot ROM would load either format.  The reasoning behind it is because Microbee's first 3.5" drives were only single sided so this could be used by the CP/M CBIOS to determine which disk type was in the drive and apply the correct CP/M DPB values to suit.

Happy to answer any other questions to assist.

**Comment by keirf** [comment]
Sounds like no issue here, although only DD DSK is supported, so maybe work needed for SD images?
I will add Microbee to the support list under CPCDSK format.

**Comment by staticmem** [comment]
I've not tried any SD images under FF so I can't comment on that.  What I would like to see is RAW image support where the disk layout is encoded in the filename.  I sent you an email back on 2018-04-16 with subject "Headerless disk images for FlashFloppy" where we touched on it as a possible new feature.

**Comment by keirf** [comment]
@staticmem raise a ticket
