### ISSUE TITLE
little star (inserted) vanishes on file "browsing" (oled + rotary encoder)

### ISSUE THREAD

**Issue by Windows-Is-Cancer** [keirf/FlashFloppy#267]
Hi Keir,

im all new to this gotek / flashfloppy thing, but im watching the scene for quite some time now, since im looking for a affordable solution for my 30yr old Roland W30 synth/sampler for years. 
yet im still in preparation phase, preparing/modding the gotek with 
- 2nd led (red no longer there)
- i2c oled display
- rotary encoder
- piezo speaker
- successfully flashed the flashflopppy 3.3a using the USB (A-A) method from Linux.
- jumpered as Drive 0 (S0)
- NOT YET tested the part with the synth. coming soon.

everything works fine so far. (speaker untested.

now for the request/question/report i want to do:

1. a little power-up beep for some initial /powerup audio feedback would be cool and helps on testing/modding. maybe even as part of the UI.

2. the little star that indicates that a file/disk is "opened" or "inserted" i love! however... with 3.3a it just goes away the very moment i "dial" to another file or dir. Even if i "dial back" to the very same file/disk without pressing any button, the star is gone. Does that mean the disk is ejected the very moment i dial/browse files ?? that would not be nice :(

as you will see, in my configuration file, i disabled all "autoselect" functionality. with a rotary encoder and 3rd pushbutton its easy to insert/eject disks quick. there i dont need/dont want it to pressure me with "timeouts". 

This is just my feedback so far.
im looking forward to test this baby in my ancient Roland synth soon. 
yours
Axel 

since microsucks seems to block and nag about uploading my FF.CFG today, im trying to add it here as "code"
`
# FlashFloppy 3.3a Config 
# for ROLAND W30 
# by Axel Werner 
# Version 2019-09-30
#
#interface = shugart
#host = unspecified
#pin34 = auto

display-type = oled-128x32-rotate
#display-type = oled-128x32
display-off-secs = 30
#oled-font = 6x13
oled-font = 8x16

write-protect = yes
    # holding eject for 2 seconds to change write/protect

image-on-startup = init

step-volume = 20
    # volume 0-20 

autoselect-file-secs = 0
autoselect-folder-secs = 0
nav-loop = no
#nav-loop = yes

#twobutton-action = zero
twobutton-action = eject
`

**Comment by keirf** [comment]
1. If you want to test that the Gotek is running at all then you can install the IO Test firmware (https://github.com/keirf/FlashFloppy/wiki/Testing-IO-Pins) and this will pulse to the speaker every couple of seconds. I'm not sure about startup sounds in the main firmware, it would probably be annoying.

2. The '*' indicates the mounted image is read-only (because you specified `write-protect=yes` in FF.CFG). I'm afraid that image navigation (ie. using the rotary encoder) does automatically eject the current image: The Gotek is hard at work when an image is mounted and is unable to navigate the FAT filesystem at the same time. Thus the firmware is somewhat 'bimodal': Either it is in navigation mode, or it is in image-inserted mode. This bimodal arrangement won't change.
