### ISSUE TITLE
Amstrad CPC6128 Super Cauldron issue

### ISSUE THREAD

**Issue by Turk182es** [keirf/FlashFloppy#43]
Hi,

I update with 0.96 firmware and still have Super Cauldron all versions doesn't work. I have blank screen. 
I have the same issue with more game with long loading.

Regards
Stephane

**Comment by keirf** [comment]
Are you using DSK? Have you tried converting to HFE? Is the game an original or a cracked version with copy protection removed? (Sorry I'm not familiar with the CPC scene and whether distribution is generally of perfect images or of cracks).

**Comment by Turk182es** [comment]
I'm using DSK not converted because since new firmware you can use DSK, that's why I onpen an issue just to let you know.
I try original version and hacked version with removed protection. Same issue.

**Comment by Turk182es** [comment]
Just try and same issue with HFE, so it is an issue with the game, I have some other games with issue if you want to investigate. Most of them are game with Side A and Side B.

**Comment by keirf** [comment]
Are they all double-sided, or are there some single-sided ones with issues?

**Comment by Turk182es** [comment]
Super Cauldron is single side

**Comment by keirf** [comment]
Ok, I had a theory involving being too slow to switch disk sides. Obviously not correct for a single-sided game! Can you send me the disk image(s), or a link to them? My email is in my Github profile page if you want to email.

**Comment by keirf** [comment]
Actually I'm being silly, all the original titles will be single-sided at a time unless disk physically flipped, duh. :)

**Comment by Turk182es** [comment]
I don’t have it right now. It I download it from CPC-Power.com

Enviado desde mi iPhone

**Comment by Turk182es** [comment]
Hi,

I sent you the 2 image disk that don't work.

Thanks for your support.

**Comment by TheFrenchy75** [comment]
Hi,

The "Super Cauldron (UK,F,G) (1993) [Original].dsk" image works fine with the HxC firmware for gotek. The converted hfe file too.
I didn't tried them with FlashFloppy yet.

**Comment by Turk182es** [comment]
The issue is with the Floppy USB.

**Comment by keirf** [comment]
Okay that's interesting thank you. Perhaps you could try the following modified firmware and see if it works with DSK or HFE?

[ff_dsk1.zip](https://github.com/keirf/FlashFloppy/files/1650027/ff_dsk1.zip)

**Comment by keirf** [comment]
By the way the cracked+trained version seems to have changed in the last day or so? I have a single-sided version with more than 40 tracks. But the new version seems to be a 40-track double-sided image, with sides A and B distributed in separate DSK files? Can I assume that neither works with FlashFloppy at the moment? ;)

**Comment by keirf** [comment]
This firmware has patches on top of 0.9.6a, I simply didn't change the version number in this firmware build.

**Comment by Turk182es** [comment]
Perfect! I will try it tonight!

Thanks

**Comment by Turk182es** [comment]
Good news !

I don't know what do the trick, the new DSK or your Firmware patch but know it work like a charm.

Thanks for your support, you can close this ticket if you want.

**Comment by keirf** [comment]
Probably it is the new image. Worth checking with latest unpatched firmware.

**Comment by Turk182es** [comment]
What the firmware patch does exactly ?

**Comment by keirf** [comment]
It alters DSK long-track handling. Rather than shrinking the bitcell size to fit the track in 200ms rotation time, it instead fixes the bitcell size and thus extends the rotation time. This is particularly relevant for the protected original DSK, which has protection tracks with overlapping sectors. The naive decode of these tracks does not overlap the sectors and hence we get a very long track (~50% longer than a normal track). If we reduce bitcell size accordingly then there is no way the host will sync to the read stream. Instead it is saner to just make the track take longer to read. The host is unlikely to care (eg. unlikely to notice that time between INDEX pulses is ~300ms rather than 200ms).

This patch is unlikely to have any effect on the cracked DSK images to be honest. So the fact the new cracked DSK works is probably because the crack is new or fixed in some way.

**Comment by Turk182es** [comment]
Thank you for your help!
