### ISSUE TITLE
suggested software for flashing Artery under Linux?

### ISSUE THREAD

**Issue by DrYak** [keirf/flashfloppy#584]
Hi!

The [linked post on MSX forum](https://www.msx.org/forum/msx-talk/hardware/goteks-with-new-guts) only mentions [Windows software for flashing](https://www.arterytek.com/download/Artery_ISP_Programmer_V1.5.46.zip)  Artey chips.

On Linux I have tried using dfu-util v0.11, but it fails at the unprotection step with:
```console
dfu-util: Wrong state after command "READ_UNPROTECT" download
```
Is there a suggestion for successfully flashing from Linux? Or trying to dust out some Windows VM and forwarding it the USB port is the only solution?
Thanks!

**Comment by keirf** [comment]
I haven't tried it I'm afraid. My guess is that dfu-util would need patching.

**Comment by ejona86** [comment]
I successfully flashed an Artery from Linux. But it turned out easy enough I didn't write it down... I have dfu-util 0.11. I think it involved "ignore the error message" and maybe "power cycle the Gotek." I might have also used lsusb to determine the device for `--device`.

**Comment by BakedSnake** [comment]
I get the same "READ_UNPROTECT" on linux. anyone has more info on how to flash on linux?

**Comment by keirf** [comment]
Beased on ejona86's response I would try ignoring the error, reconnect the Gotek, and try the line
`sudo dfu-util -a 0 -D FF_Gotek-v3.*.dfu`

**Comment by prosper00** [comment]
I just used the UART / serial bootloader. Worked great. Self-updates from the USB stick work well too to keep things updated.

**Comment by BakedSnake** [comment]
So, I ignored the error and continued with the next command. After that I had to update my gotek with the upd file and everything works.

I was able to boot my mpc2000.

So I guess just dfu-util is enough.

Thanks

**Comment by conloos** [comment]
Hello @all,

I had some problems to flash the firmware with a USB-TTL. 
Following my solution based on a thread at the [Amiga forum](http://eab.abime.net/showthread.php?p=1175795).

My environment is: Ubuntu 21.04 with stm32flash 0.5 and a USB TTL from D-SUN.

First the read protection has to be switched off:
$ sudo stm32flash -k / dev / ttyUSB0
Then clear the memory:
$ sudo stm32flash -o / dev / ttyUSB0
Finally, the firmware can be flashed without any problems.
$ sudo stm32flash -vw FF_Gotek-v3.29.hex / dev / ttyUSB0

Switching off the flash write protection was acknowledged with an error:
$ sudo stm32flash -u / dev / ttyUSB0
stm32flash 0.5

http://stm32flash.sourceforge.net/

Interface serial_posix: 57600 8E1
Version: 0x32
Option 1: 0x46
Option 2: 0x01
Device ID: 0x0410 (STM32F10xxx Medium-density)
- RAM: Up to 20KiB (512b reserved by bootloader)
- Flash: Up to 128KiB (size first sector: 4x1024)
- RAM option: 16b
- System RAM: 2KiB
Write-unprotecting flash
Got NACK from device on command 0x73
Failed to write-unprotect flash

**Comment by hugoduraes** [comment]
I wonder if using dfu-utilon a mac would work too! 🤔

**Comment by coredump4** [comment]
I would love it if it worked on Macs.  Under macOS Monterey, with dfu-util v0.11 and libusb v1.0.24 built from Mac Ports, I got this when trying to erase an STM32F105:
`dfu-util: dfuse_download: libusb_control_transfer returned -7 (LIBUSB_ERROR_TIMEOUT)`

**Comment by hugoduraes** [comment]
It actually worked for me with the same errors on the 1st command, as described above.

**Comment by Olas-Audio** [comment]
Hi everyone. A few years ago, I got an Agilent 54622A oscilloscope for about 100 USD, a real bargain and the truth is that it is an excellent measurement equipment, despite being just 100 MHz. I just want to share the methodology that I followed to be able to use a Gotek floppy emulator. Without having read this issue, I decided to buy the cheapest emulator of this brand (34 USD shipping included), it’s an SFR1M44-DU26 SFRC2D.B version. So, there is no need to buy an expensive type to perform this operation.

Step 1. Download FlashFloppy version 3.29 (I think 3.3 could also be used).
https://github.com/keirf/FlashFloppy/wiki/Downloads

Step 2. Download the file Artery_ISP_Programmer_V1.5.46 or later and install the driver “Artery_DFU_DriverInstall.exe”.
https://www.arterytek.com/en/product/AT32F415.jsp#Resource
https://www.arterytek.com/download/TOOL/Artery_ISP_Programmer_V2.0.06.zip

[Artery_ISP_Programmer_V1.5.46.zip](https://github.com/keirf/flashfloppy/files/9691279/Artery_ISP_Programmer_V1.5.46.zip)

Step 3. Prepare the PCB for flashing according to the follow images:

![Paso 1](https://user-images.githubusercontent.com/114833459/193429566-b961e25c-6a14-482e-a424-c8c074eb1a8c.png)
This version uses the Artery microcontroller.

![Paso 2](https://user-images.githubusercontent.com/114833459/193429594-d50c71f6-512d-4063-9542-aa897f8e5c51.png)
SFRC2D.B version.

![Paso 3](https://user-images.githubusercontent.com/114833459/193429638-2dedec9d-4c4a-445b-b1c0-83d9f5e735e9.png)
I used a USB type A cable on one end and on the other side I exposed the wires so I could solder them to the PCB. I performed this step since I didn't have a USB A-A type cable.

![Paso 4](https://user-images.githubusercontent.com/114833459/193429657-488d856c-7bea-45c2-9f47-dc8b00d710e4.png)
I soldered the wires in the shown sequence to the base of the USB connector on the PCB, the layout is as follows:
|GND-black|D+ Green|D- White|+V-Red|

![Paso 5](https://user-images.githubusercontent.com/114833459/193429704-be276406-6800-43d2-a941-f8445da027aa.png)
I soldered a 5-pin header to put a jumper between Boot-3V pins. I only left the S1 jumper in place.

![image](https://user-images.githubusercontent.com/114833459/193430053-a257c380-4e53-4fcb-a5bc-6b86b84f5d8f.png)
Install the driver.

![image](https://user-images.githubusercontent.com/114833459/193429722-95d99dd2-9118-436e-b14a-0c77a14ffce9.png)
Then run the app “ArteryISSProgrammer.exe”.

![image](https://user-images.githubusercontent.com/114833459/193429757-888a5805-b407-4d16-a5ff-90c4199e5abb.png)
Select USB DFU as the port type. Then we proceed to connect USB cable.

![image](https://user-images.githubusercontent.com/114833459/193429762-f76b03f8-55de-47c8-96a9-bae1d8d5630d.png)
Select language and click next

![image](https://user-images.githubusercontent.com/114833459/193429767-259eaa6f-7baf-4698-9f0b-f72a56e3e2d3.png)
Click next

![image](https://user-images.githubusercontent.com/114833459/193429774-550fdec7-92f6-45b7-9975-b754c0a96946.png)
Click next

![image](https://user-images.githubusercontent.com/114833459/193429786-b6106f9e-a97b-4445-9d6d-2d6676cfe45e.png)
You must select Enable/disable protection, click yes from the dialog box and then click next

![image](https://user-images.githubusercontent.com/114833459/193429795-fd11ade7-acfb-4889-85da-76007c920e37.png)
Wait until it’s done the click back

![image](https://user-images.githubusercontent.com/114833459/193429803-a266e3b0-1303-4b03-b83d-2e23af991bfc.png)
Click Download to device and then click add

![image](https://user-images.githubusercontent.com/114833459/193429810-34fd0234-8f37-4041-b5a8-2594f63344a7.png)
Look for the Hex file of the version you want to install, in my case 3.29.

![image](https://user-images.githubusercontent.com/114833459/193429819-8154a72c-a5a3-4290-b08b-a4d2bd55a4cc.png)
Select Global erase and verify after download then click next

![image](https://user-images.githubusercontent.com/114833459/193429826-305b7531-f0c3-4fc3-b664-fdb528bebff5.png)

![image](https://user-images.githubusercontent.com/114833459/193429839-aecf62e1-af2b-494e-bf07-250957352f18.png)
Finally click close. You can unplug the USB cable from the computer.

Now you can desolder the resistors RA, RB and RC. The memory IC does not need to be preserved. I removed it so I could use it in some other project later on.

![image](https://user-images.githubusercontent.com/114833459/193429920-15ca3c34-7b29-4887-b3e3-b8ef4454c2fb.png)
![Paso 6](https://user-images.githubusercontent.com/114833459/193429946-01c33a11-35b9-4eab-90b7-dee5d269b9e8.png)
Don't forget to remove Jumper Boot-3.3V.

Finally, it is necessary to prepare you USB device. Give it a format FAT32 and then you need to copy the "1m44_fat12.img" file into the main directory of the USB that you just formatted.
https://github.com/andrewpono/TDS3000-Series-Gotek-FlashFloppy/blob/main/1m44_fat12.img

That’s it, your scope should be ready to save Images into your USB stick. The file storing time it’s slow but it’s definitely more convenient than to use a Floppy Disk.

Cheers and enjoy your measurement!
