### ISSUE TITLE
Small then usual images support

### ISSUE THREAD

**Issue by AdamKlob** [keirf/FlashFloppy#587]
I'm using GOEX floppy emulator which i version of Gotek for Atari ST (https://centuriontech.eu/product/goex4st/)

I have a floppy image that works perfectly well with software Atari STE emulators (Hatari, Saint), but when I try to load it into GOEX installed in real Atari ST it seems that firmware fails - nothing is readable and I have weird dots on led screen
[dsr_intro_atari_1040ste.zip](https://github.com/keirf/FlashFloppy/files/7736805/dsr_intro_atari_1040ste.zip)

**Comment by keirf** [comment]
I don't know about the weird dots. My Gotek gives `E31` which means the image is invalid. This is because the image is only 80kB in size, but FlashFloppy uses the image size to work out the track geometry (eg, 9 sectors per track, 10 sectors per track, or whatever).

So, pad the image up to the appropriate size (800kB I believe, in this case) and try again. In fact, here it is:

[dsr_intro_atari_1040ste_padded.zip](https://github.com/keirf/FlashFloppy/files/7736909/dsr_intro_atari_1040ste_padded.zip)
