### ISSUE TITLE
Windows won't recognize Gotek SFRKC30.AT3

### ISSUE THREAD

**Issue by bromine3** [keirf/flashfloppy#811]
I have read and re-read the instructions but I still cannot get Windows to recognize my Gotek. Any suggestions?

**Comment by keirf** [comment]
Jumpers at S1 and JC should be sufficient. Along with a suitable image file on your USB drive (eg. a 1.44MB IMG file).

**Comment by bromine3** [comment]
So I believe I have the jumpers in the correct place. I'm using the usb-a to usb-a method but still I cannot get the Artery software to see my device.

**Comment by keirf** [comment]
I see. The problem is to get the Gotek recognised as a usb dfu device. At the very least you should here the device hotplug chime when inserted, Windows should look for a driver, device should appear in device manager under usb devices, etc. If that doesn't happen then you misjumpered or the Gotek is bad or quite possibly your cable is bad.

**Comment by bromine3** [comment]
Ok, thank you for the insight. Are there any gotek models that you would recommend?

**Comment by keirf** [comment]
I personally recommend the AT32F435 based models, which have PCB model number SFRKC30.AT4.35. See https://github.com/keirf/FlashFloppy/wiki/Gotek-Models

As a bonus these will generally be ready flashed with FlashFloppy, as there is no other "factory firmware" for this model.

However, this doesn't really have anything to do with your current problem. Your Gotek absolutely should identify as a programmable device to Windows.
